from __future__ import annotations

from typing import Optional, Protocol, Tuple
from typing_extensions import Self
from uuid import UUID

from ..domain.entities import FieldSchema, FieldValue


class EventBus(Protocol):
    def publish(self, event) -> None: ...
    def publish_many(self, events) -> None: ...


class FieldSchemaRepo(Protocol):
    async def get_by_kind(self, kind: str) -> Optional[FieldSchema]: ...
    async def get(self, schema_id: UUID) -> Optional[FieldSchema]: ...
    async def save(self, schema: FieldSchema) -> None: ...


class FieldValueRepo(Protocol):
    async def get_by_entity(self, entity_id: UUID) -> Optional[Tuple[FieldValue, ...]]: ...
    async def save(self, entity_id: UUID, schema_version: int, values: Tuple[FieldValue, ...]) -> None: ...
    async def delete_by_entity(self, entity_id: UUID) -> None: ...


class DynamicFieldUoW(Protocol):
    @property
    def field_schemas(self) -> FieldSchemaRepo: ...
    @property
    def field_values(self) -> FieldValueRepo: ...
    @property
    def event_bus(self) -> EventBus: ...

    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, *args) -> None: ...
    async def commit(self) -> None: ...
